CS3219-AY2223S1/cs3219-project-ay2223s1-g5

backend/package-lock.json
backend/package.json
backend/src/match/match.gateway.ts
backend/src/match/match.service.module.ts
backend/src/match/match.service.ts
frontend/src/pages/WaitingPage.tsx
shared/src/types/api/match.dto.ts

This PR only contains the match finding part
Disconnection will be handled in a separate PR
Closes #79

feat: integrate matching service with web sockets

---

frontend/src/hooks/useUsers.ts
frontend/src/pages/WaitingPage.tsx

feat: fetch usernames for waiting page

---

backend/.env.example
backend/.eslintrc.js
backend/src/core/config/config.schema.ts
backend/src/twilio/mock.twilio.service.ts
backend/src/twilio/twilio.service.module.ts
backend/src/twilio/twilio.service.ts
backend/src/verification/verification.controller.ts
backend/src/verification/verification.service.ts
frontend/src/components/Center.tsx
frontend/src/hooks/useAuth.ts
frontend/src/pages/VerificationPage.tsx
frontend/src/routes/app.routes.tsx
shared/.eslintrc.js
shared/src/types/api/auth.dto.ts

feat: implement email verification flow

---

frontend/src/components/NavigationBar.tsx
frontend/src/routes/nav.routes.tsx

feat: add logout button

---

frontend/src/components/Editor.tsx
frontend/src/components/Question.tsx
frontend/src/components/StyledButton.tsx
frontend/src/components/TextButton.tsx
frontend/src/layouts/SidebarLayout.tsx
frontend/src/pages/DashboardPage.tsx
frontend/src/pages/RoomPage.tsx
frontend/src/routes/app.routes.tsx
frontend/src/utils/theme.tsx

feat: add room page

---

backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/jwt.strategy.ts
backend/src/auth/ws.guard.ts
backend/src/core/prisma.service.module.ts
backend/src/match/match.service.module.ts
backend/src/redis/redis.service.module.ts
backend/src/twilio/twilio.service.module.ts
backend/src/user/user.service.module.ts
frontend/src/components/NavigationBar.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/hooks/useAuth.ts

feat: complete logout workflow

---

backend/src/app.module.ts
backend/src/match/match.gateway.ts
backend/src/match/match.module.ts
backend/src/match/match.service.module.ts
backend/src/match/match.service.ts
backend/src/redis/redis.service.ts
backend/src/room/room.gateway.ts
backend/src/room/room.module.ts
backend/src/room/room.service.module.ts
backend/src/room/room.service.ts
frontend/src/App.tsx
frontend/src/pages/RoomPage.tsx
frontend/src/pages/VerificationPage.tsx
frontend/src/pages/WaitingPage.tsx
frontend/src/routes/ProtectedRoute.tsx
frontend/src/routes/app.routes.tsx
shared/src/constants/events/index.ts
shared/src/constants/events/match.ts
shared/src/constants/events/room.ts
shared/src/constants/index.ts
shared/src/constants/namespaces.ts

feat: handle match disconnection

---

frontend/src/pages/DifficultySelectionPage.tsx

feat: implement difficulty selection page

---

backend/src/user/reset-password.service.ts
backend/src/user/user.service.ts
backend/src/verification/verification.service.ts

fix: convert emails to lowercase

---

frontend/src/components/Timer.tsx
frontend/src/pages/QueuePage.tsx

feat: queue page timer

---

backend/src/match/match.service.ts

fix: prevent users from matching with themselves

---

backend/prisma/migrations/20220920142517_question/migration.sql
backend/prisma/migrations/20220922144745_questions/migration.sql
backend/prisma/schema.prisma
project.code-workspace

Contains new database tables.
Run the following to update your database and Prisma Client: `npm run on-backend migration:run && npm run on-backend prisma:gen`.

feat: create question bank schema

---

backend/src/user/user.controller.ts
frontend/src/components/forms/LoginForm.tsx
frontend/src/components/forms/RequestVerificationEmailForm.tsx
frontend/src/hooks/useUsers.ts
frontend/src/pages/RequestVerificationEmailPage.tsx
frontend/src/pages/VerificationPage.tsx
frontend/src/routes/app.routes.tsx
shared/src/types/api/auth.dto.ts
shared/src/types/api/index.ts
shared/src/types/api/user.dto.ts

Closes #107. Closes #111. Closes #112.

feat: resend verification email

---

backend/src/judge/judge.service.ts
backend/src/judge/middleware/cpp.ts
backend/src/judge/middleware/javascript.ts
backend/src/judge/middleware/python.ts

feat: add javascript, python and cpp middleware

---

backend/src/user/user.controller.ts
frontend/src/components/forms/UpdatePasswordForm.tsx
frontend/src/components/modals/UpdatePasswordModal.tsx
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useUsers.ts
frontend/src/pages/AccountSettingPage.tsx
frontend/src/pages/VerificationPage.tsx

feat: implement update password logic

---

backend/src/judge/judge.service.ts
backend/src/judge/middleware/cpp.ts
backend/src/judge/middleware/java.ts
backend/src/judge/middleware/javascript.ts
backend/src/judge/middleware/middleware.ts
backend/src/judge/middleware/python.ts

Arrays are printed differently for each language. E.g. `[ 1, 2 ]` `[1,2]`, `[1, 2]`
So we will compare the actual and expected output in the submitted code
Judge0 will return `True` or `False` in stdout
Part of #207

feat: assert actual result and expected result are equal in code

---

backend/src/judge/judge.service.ts
backend/src/question/question.service.ts
backend/src/queue/queue.gateway.ts
backend/src/queue/queue.service.ts
backend/src/room/room.gateway.ts
backend/src/room/room.interface.ts
backend/src/room/room.service.ts
frontend/src/components/Editor.tsx
frontend/src/pages/DifficultySelectionPage.tsx
frontend/src/pages/QueuePage.tsx
frontend/src/pages/RoomPage.tsx
shared/src/types/api/index.ts
shared/src/types/api/queue.dto.ts
shared/src/types/api/room.dto.ts
shared/src/types/base/difficulty.ts
shared/src/types/base/index.ts
shared/src/types/base/language.ts

Closes #187. Closes #188. Closes #189. Closes #190.

feat: implement language selection

---

backend/src/editor/editor.service.ts
backend/src/question/question.service.ts
backend/src/queue/queue.gateway.ts
backend/src/queue/queue.service.ts
backend/src/room/room.gateway.ts
backend/src/room/room.interface.ts
backend/src/room/room.service.module.ts
backend/src/room/room.service.ts
shared/src/types/api/room.dto.ts

feat: fill solution template on first document load

---

frontend/src/components/room/Question.tsx
frontend/src/components/room/QuestionSubmissionPanel.tsx
frontend/src/hooks/useQuestion.ts
frontend/src/pages/RoomPage.tsx
package-lock.json

feat: display question on frontend

---

backend/src/judge/judge.service.module.ts
backend/src/judge/judge.service.ts
backend/src/question/question.service.ts
backend/src/room/room.gateway.ts
backend/src/room/room.module.ts
shared/src/constants/events/room.ts
shared/src/types/api/index.ts
shared/src/types/api/room.dto.ts

Closes #226 
Other things to be done:
- Integrate with frontend
- Prevent users from making multiple submissions before Judge0 returns result

feat: integrate JudgeService with RoomGateway

---

backend/src/judge/judge.service.module.ts
backend/src/judge/judge.service.ts
backend/src/room/room.gateway.ts
shared/src/constants/events/room.ts
shared/src/types/api/room.dto.ts

feat: prevent users from making multiple submissions

---

frontend/src/contexts/SocketsContext.tsx

fix: socket context

---

backend/src/judge/middleware/java.ts
frontend/src/components/room/QuestionSubmissionPanel.tsx
frontend/src/components/room/Submissions.tsx
frontend/src/hooks/useSubmissions.ts
frontend/src/pages/RoomPage.tsx

feat: display submissions on frontend

---

backend/src/judge/judge.service.ts
frontend/src/components/room/Submissions.tsx

feat: compare Judge0 result

---

frontend/src/components/charts/AttemptSummaryChart.tsx
frontend/src/components/charts/DurationSummaryChart.tsx
frontend/src/components/charts/NetworkChart.tsx
frontend/src/components/charts/SubmissionsHeatmap.tsx
frontend/src/components/settings/ChangePassword.tsx
frontend/src/pages/DashboardPage.tsx

Managed to clear in time for demo

feat: add submission heatmap

---

backend/src/judge/judge.service.ts
backend/src/judge/middleware/cpp.ts
backend/src/judge/middleware/java.ts
backend/src/judge/middleware/javascript.ts
backend/src/judge/middleware/middleware.ts
backend/src/judge/middleware/python.ts

Print output to stderr

---

backend/src/queue/queue.gateway.ts
backend/src/queue/queue.service.ts

fix: duplicate connection bug

---

backend/src/queue/queue.service.ts
backend/src/queue/tests/queue.e2e.spec.ts

I can't think of a better way to fix the race conditions

test: add test for queue websocket

---

backend/src/editor/editor.service.ts
frontend/src/contexts/EditorContext.tsx

revert: standardize editor line endings

---

.env.example
README.md
backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
package-lock.json
package.json
serverless/package.json
shared/package.json

chore: update README

---

frontend/src/components/forms/ResetPasswordForm.tsx
frontend/src/components/forms/SignUpForm.tsx
frontend/src/components/forms/UpdatePasswordForm.tsx

fix: update password error message

---

frontend/src/components/room/Submissions.tsx

fix: reorder submissions table indexes

---

frontend/src/pages/DashboardPage.tsx

fix: reverse past sessions sort order
